spring:
  security:
    oauth2:
      client:
        provider:
          google:
            # /.well-known/openid-configuration will be added by org.springframework.security.oauth2.client.registration.ClientRegistrations
            # From https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig
            # OpenID Providers supporting Discovery MUST make a JSON document available at the path formed by
            # concatenating the string /.well-known/openid-configuration to the Issuer.
            issuer-uri: https://accounts.google.com

logging:
  level:
    org:
      springframework:
        web:
          client:
            # To view some of the exchange
            RestTemplate: DEBUG
    com.example.demoopenid.DemoOpenidApplication: DEBUG
