spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    schema: classpath:acl-schema.sql
    data: classpath:acl-data.sql
  jpa:
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


logging:
  level:
    org:
      spring:
        framework:
          jdbc:
            core: DEBUG
      springframework:
        security: DEBUG
