env:
  es6: true
  node: true
extends:
  - google
  - plugin:security/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
